version: '3.4'

services:
  outpost-logistics:
    image: ${DOCKER_REGISTRY-}outpost-logistics
    build:
      context: .
      dockerfile: outpost-logistics/Dockerfile
    ports:
     - 8081:443
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyAppDb;User=sa;Password=Password123;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"